name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          target: website
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/cloud-server:latest

  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install --global pnpm

      # - name: Cache .pnpm-store
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.pnpm-store
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: SFTP Upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: sftp.drewh.net
          username: root
          key: ${{secrets.SFTP_KEY}}
          uploads: |
            ./dashboard/dist => /root/sites/dashboard
          port: 22

  notify-watchtower:
    needs: [build-server]
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://watchtower.drewh.net/v1/update'
          preventFailureOnNoResponse: "true"
          method: 'GET'
          customHeaders: '{"Authorization": "Bearer ${{secrets.WATCHTOWER_KEY}}"}'

